// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvNMGX8s0nhITWC7Pjyeb5T5lfEX5jhBk',
    appId: '1:1035893600391:web:dd8be2acf0a4f81ef3c822',
    messagingSenderId: '1035893600391',
    projectId: 'pvt15-car-spotting',
    authDomain: 'pvt15-car-spotting.firebaseapp.com',
    storageBucket: 'pvt15-car-spotting.appspot.com',
    measurementId: 'G-4KGL8FN1M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOCARoRRaZuBo6Dhspq1yLzsKskEzoDWM',
    appId: '1:1035893600391:android:b0199a0b0235fe95f3c822',
    messagingSenderId: '1035893600391',
    projectId: 'pvt15-car-spotting',
    storageBucket: 'pvt15-car-spotting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlr2U2fBzCbDlrN-2xOpI3z-bu02pxXaQ',
    appId: '1:1035893600391:ios:f3bb56a10330d9c9f3c822',
    messagingSenderId: '1035893600391',
    projectId: 'pvt15-car-spotting',
    storageBucket: 'pvt15-car-spotting.appspot.com',
    iosClientId: '1035893600391-4nqnvnvh1ob06ansmekbr1tsgtu0g02o.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMapsInFlutter',
  );
}
